# Dracula Color Palette
set -l foreground #d7dae0
set -l selection #3e4058
set -l gray #6e6c7c
set -l red #e28c8c
set -l orange #f7c196
set -l yellow #eadda0
set -l green #b3e1a3
set -l purple #c6aae8
set -l pink #f0afe1
set -l blue #a4b9ef

# Syntax Highlighting Colors
set -g fish_color_normal $foreground
set -g fish_color_command $blue
set -g fish_color_keyword $pink
set -g fish_color_quote $yellow
set -g fish_color_redirection $red
set -g fish_color_end $orange
set -g fish_color_error $purple
set -g fish_color_param $blue
set -g fish_color_gray $gray
set -g fish_color_selection --background=$selection
set -g fish_color_search_match --background=$selection
set -g fish_color_operator $green
set -g fish_color_escape $blue
set -g fish_color_autosuggestion $gray

# Completion Pager Colors
set -g fish_pager_color_progress $gray
set -g fish_pager_color_prefix $pink
set -g fish_pager_color_completion $foreground
set -g fish_pager_color_description $gray
