# Dracula Color Palette
set -l foreground #D7DAE0
set -l selection #3e4058
set -l gray #6E6C7C
set -l red #E28C8C
set -l orange #F7C196
set -l yellow #EADDA0
set -l green #B3E1A3
set -l purple #C6AAE8
set -l pink #F0AFE1
set -l blue #A4B9EF

# Syntax Highlighting Colors
set -g fish_color_normal $foreground
set -g fish_color_command $blue
set -g fish_color_keyword $pink
set -g fish_color_quote $yellow
set -g fish_color_redirection $red
set -g fish_color_end $orange
set -g fish_color_error $purple
set -g fish_color_param $blue
set -g fish_color_gray $gray
set -g fish_color_selection --background=$selection
set -g fish_color_search_match --background=$selection
set -g fish_color_operator $green
set -g fish_color_escape $blue
set -g fish_color_autosuggestion $gray

# Completion Pager Colors
set -g fish_pager_color_progress $gray
set -g fish_pager_color_prefix $pink
set -g fish_pager_color_completion $foreground
set -g fish_pager_color_description $gray
